### ISSUE TITLE
Import error with python 3.7 but not 3.8 (importlib metadata)

### ISSUE THREAD

**Issue by DanielTakeshi** [HumanCompatibleAI/imitation#504]
According to the setup.py file:

https://github.com/HumanCompatibleAI/imitation/blob/c1a992a75b6ac9aa708b798a47ea327ca81150e7/setup.py#L98

It seems like Python 3.7 or higher is required. However the example command in the README does not seem to work out of the box for me with 3.7 but it does with 3.8.

I'm using **Ubuntu 18.04.6** and here are the steps to reproduce with clean conda environments (conda version 4.13), _assuming we git clone this repo (main branch) and are in the directory_ so that a `pip install -e .` works. I'm using this commit https://github.com/HumanCompatibleAI/imitation/commit/c1a992a75b6ac9aa708b798a47ea327ca81150e7 which is the most recent one as of me writing this issue.

For Python 3.7:

```
conda create --name imitation-python37 python=3.7 -y
conda activate imitation-python37
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch -y
pip install -e .
```

For 3.8, it's the sample except the first command uses 3.8 instead of 3.7 (and I re-named to `imitation-python38` for obvious reasons).

Command line output for 3.7 using the command that's on the README to train PPO on pendulum:

```
(imitation-python37) seita@takeshi:~/human_compatible_imitation/imitation (master)$ python -m imitation.scripts.train_rl with pendulum common.fast train.fast rl.fast fast common.log_dir=quickstart/rl/
Traceback (most recent call last):
  File "/home/seita/miniconda3/envs/imitation-python37/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/seita/miniconda3/envs/imitation-python37/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/seita/human_compatible_imitation/imitation/src/imitation/__init__.py", line 3, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (/home/seita/miniconda3/envs/imitation-python37/lib/python3.7/importlib/__init__.py)
(imitation-python37) seita@takeshi:~/human_compatible_imitation/imitation (master)$ 
```

For 3.8 the same command will run to completion:

```
(imitation-python38) seita@takeshi:~/human_compatible_imitation/imitation (master)$ python -m imitation.scripts.train_rl with pendulum common.fast train.fast rl.fast fast common.log_dir=quickstart/rl/
WARNING - rl - Added new config entry: "rl_kwargs.batch_size"
WARNING - rl - Added new config entry: "rl_kwargs.gamma"
WARNING - rl - Added new config entry: "rl_kwargs.learning_rate"
INFO - train_rl - Running command 'train_rl'
INFO - train_rl - Started run with ID "1"
INFO - imitation.scripts.common.common - Logging to quickstart/rl/
INFO - imitation.scripts.common.rl - RL algorithm: <class 'stable_baselines3.ppo.ppo.PPO'>
INFO - imitation.scripts.common.rl - Policy network summary:
 FeedForward32Policy(
  (features_extractor): NormalizeFeaturesExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
    (normalize): RunningNorm()
  )
  (mlp_extractor): MlpExtractor(
    (shared_net): Sequential(
      (0): Linear(in_features=3, out_features=32, bias=True)
      (1): Tanh()
      (2): Linear(in_features=32, out_features=32, bias=True)
      (3): Tanh()
    )
    (policy_net): Sequential()
    (value_net): Sequential()
  )
  (action_net): Linear(in_features=32, out_features=1, bias=True)
  (value_net): Linear(in_features=32, out_features=1, bias=True)
)
INFO - root - Saved policy to quickstart/rl/policies/000000000002
--------------------------
| time/              |   |
|    fps             | 4 |
|    iterations      | 1 |
|    time_elapsed    | 0 |
|    total_timesteps | 2 |
--------------------------
INFO - root - Saved policy to quickstart/rl/policies/000000000004
-----------------------------------------
| time/                   |             |
|    fps                  | 7           |
|    iterations           | 2           |
|    time_elapsed         | 0           |
|    total_timesteps      | 4           |
| train/                  |             |
|    approx_kl            | 0.005149454 |
|    clip_fraction        | 0           |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.41       |
|    explained_variance   | -0.0449     |
|    learning_rate        | 0.001       |
|    loss                 | 9.67        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0299     |
|    std                  | 0.99        |
|    value_loss           | 20.3        |
-----------------------------------------
INFO - root - Rollout stats: {'n_traj': 400, 'return_min': -48.76757344973204, 'return_mean': -19.31970926514717, 'return_std': 14.899799208464888, 'return_max': -0.029246572231279164, 'len_min': 5, 'len_mean': 5.0, 'len_std': 0.0, 'len_max': 5}
INFO - root - Dumped demonstrations to quickstart/rl/rollouts/final.pkl.
INFO - root - Saved policy to quickstart/rl/policies/final
INFO - train_rl - Result: {'n_traj': 2, 'monitor_return_len': 2, 'return_min': -2.1894811391830444, 'return_mean': -1.7372726425528526, 'return_std': 0.4522084966301918, 'return_max': -1.2850641459226608, 'len_min': 5, 'len_mean': 5.0, 'len_std': 0.0, 'len_max': 5, 'monitor_return_min': -24.414174, 'monitor_return_mean': -19.371377, 'monitor_return_std': 5.042796999999999, 'monitor_return_max': -14.32858}
INFO - train_rl - Completed after 0:00:02
```

The issue seems to be this `importlib` which has some changes from 3.7 to 3.8 see for example:

https://stackoverflow.com/questions/59216175/importerror-cannot-import-name-metadata-from-importlib

Does this package thus require 3.8 or higher?

**Comment by DanielTakeshi** [comment]
Oh I see this:
https://github.com/HumanCompatibleAI/imitation/commit/242b15bd70a9278e4477b4197ffd9ee50fcda5b9
That seems to suggest that 3.8 is required as of a few days ago?

Feel free to close if this is correct

**Comment by levmckinney** [comment]
@AdamGleave should we update the `setup.py` to drop support for 3.7?

**Comment by AdamGleave** [comment]
Thanks for catching this. Yes, inclined to drop 3.7 support. Does anyone object? We can keep 3.7 support by using the `importlib_metadata` backport.
