### ISSUE TITLE
Gym related AttributeError, can't create `make_vec_env`

### ISSUE THREAD

**Issue by robinsonkwame** [HumanCompatibleAI/imitation#720]
## Bug description
Gym/Gymnasium related AttributeError, can't create `make_vec_env`

## Steps to reproduce
Following the start of the preference experiment documentation,

```
import numpy as np

from stable_baselines3 import PPO
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.ppo import MlpPolicy

from imitation.algorithms import preference_comparisons
from imitation.policies.base import FeedForward32Policy, NormalizeFeaturesExtractor
from imitation.rewards.reward_nets import BasicRewardNet
from imitation.rewards.reward_wrapper import RewardVecEnvWrapper
from imitation.util.networks import RunningNorm
from imitation.util.util import make_vec_env

rng = np.random.default_rng(0)

venv = make_vec_env("Pendulum-v1", rng=rng)
```
output
```
Traceback (most recent call last):
  File "preference_comparsion_script.py", line 17, in <module>
    venv = make_vec_env("Pendulum-v1", rng=rng)
  File "/opt/conda/lib/python3.8/site-packages/imitation/util/util.py", line 152, in make_vec_env
    return DummyVecEnv(env_fns)
  File "/home/mamba/stable-baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 42, in __init__
    VecEnv.__init__(self, len(env_fns), env.observation_space, env.action_space, env.render_mode)
  File "/opt/conda/lib/python3.8/site-packages/gymnasium/core.py", line 282, in __getattr__
    return getattr(self.env, name)
  File "/opt/conda/lib/python3.8/site-packages/gym/core.py", line 238, in __getattr__
    return getattr(self.env, name)
  File "/opt/conda/lib/python3.8/site-packages/gym/core.py", line 238, in __getattr__
    return getattr(self.env, name)
AttributeError: 'PendulumEnv' object has no attribute 'render_mode'
```

## Environment
- Operating system and version: `mambaorg/micromamba:1.4.1-focal-cuda-11.7.1` (Docker)
- Python version: `Python 3.8.16`
- Output of `pip freeze --all`:

absl-py==1.4.0
alabaster==0.7.13
ale-py==0.8.1
attrs==23.1.0
AutoROM==0.6.1
AutoROM.accept-rom-license==0.6.1
Babel==2.12.1
black==23.3.0
cachetools==5.3.0
certifi==2023.5.7
chai-sacred==0.8.3
charset-normalizer==3.1.0
click==8.1.3
cloudpickle==2.2.1
colorama==0.4.6
contourpy==1.0.7
coverage==7.2.6
cycler==0.11.0
docopt==0.6.2
docutils==0.18.1
exceptiongroup==1.1.1
execnet==1.9.0
Farama-Notifications==0.0.4
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1681839547898/work
fonttools==4.39.4
fsspec==2023.5.0
gitdb==4.0.10
GitPython==3.1.31
gmpy2 @ file:///home/conda/feedstock_root/build_artifacts/gmpy2_1666808683138/work
google-auth==2.18.1
google-auth-oauthlib==1.0.0
grpcio==1.54.2
gym==0.21.0
gymnasium==0.28.1
huggingface-hub==0.14.1
huggingface-sb3==2.2.4
idna==3.4
imagesize==1.4.1
imitation==0.3.2
importlab==0.8
importlib-metadata==6.6.0
importlib-resources==5.12.0
iniconfig==2.0.0
isort==5.12.0
jax-jumpy==1.0.0
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
joblib==1.2.0
jsonpickle==3.0.1
kiwisolver==1.4.4
libcst==0.4.10
livereload==2.6.3
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1674135809652/work
matplotlib==3.7.1
mdurl==0.1.2
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1678228039184/work
munch==2.5.0
mypy==1.3.0
mypy-extensions==1.0.0
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1680692919326/work
ninja==1.11.1
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1682210232610/work
oauthlib==3.2.2
opencv-python-headless==4.7.0.72
packaging==23.1
pandas==2.0.1
pathspec==0.11.1
Pillow==9.5.0
pip==21.0
platformdirs==3.5.1
pluggy==1.0.0
protobuf==4.23.1
psutil==5.9.5
py-cpuinfo==9.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydot==1.4.2
pyenchant==3.2.2
pygame==2.4.0
pyglet==1.5.27
Pygments==2.15.1
pyparsing==3.0.9
pytest==7.3.1
pytest-cov==4.1.0
pytest-env==0.8.1
pytest-xdist==3.3.1
python-dateutil==2.8.2
pytype==2023.5.8
pytz==2023.3
PyYAML==6.0
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.3.5
rsa==4.9
ruff==0.0.270
scikit-learn==1.2.2
scipy==1.10.1
seals==0.1.5
setuptools==65.5.0
Shimmy==0.2.1
six==1.16.0
smmap==5.0.0
snowballstemmer==2.2.0
sphinx==6.2.1
sphinx-autobuild==2021.3.14
sphinx-autodoc-typehints==1.23.0
sphinx-copybutton==0.5.2
sphinx-rtd-theme==1.2.1
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib-spelling==8.0.0
# Editable install with no version control (stable-baselines3==2.0.0a10)
-e /home/mambauser/stable-baselines3
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1684180540116/work
tabulate==0.9.0
tensorboard==2.13.0
tensorboard-data-server==0.7.0
threadpoolctl==3.1.0
toml==0.10.2
tomli==2.0.1
torch @ file:///home/conda/feedstock_root/build_artifacts/pytorch-recipe_1680607340255/work
tornado==6.3.2
tqdm==4.65.0
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1684927677879/work
typing-inspect==0.8.0
tzdata==2023.3
urllib3==1.26.16
wasabi==1.1.1
Werkzeug==2.3.4
wheel==0.40.0
wrapt==1.15.0
zipp==3.15.0

**Comment by robinsonkwame** [comment]
Likely related, when trying to work with the [quick_example.py](https://github.com/HumanCompatibleAI/imitation/blob/master/examples/quickstart.py) I see 
```
/home/mamba/stable-baselines3/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
```
it also errors out with a Gym related error, `AttributeError: 'Box' object has no attribute 'is_np_flattenable'`

**Comment by robinsonkwame** [comment]
The problem was likely caused by installing `baselines3` and then installing `imitation`; installing `imitation` alone uses older versions of `gym`, avoids `baseline3` patching, and runs this and other examples as expected.

e.g.
Dockerfile
```{docker}
FROM humancompatibleai/imitation:base
RUN pip install imitation
WORKDIR /tmp
ENTRYPOINT ["python3"]
```
Bash
`docker run --rm -v "$(pwd)":/tmp imitation  preference_comparsion_script.py` runs the above without error.
